### ISSUE TITLE
工具报错了，麻烦更新下

### ISSUE THREAD

**Issue by weishengbin** [movescriptions/tools#2]
![360截图20240104221715037](https://github.com/movescriptions/tools/assets/21980761/dd0b4eeb-c34e-4f86-aa7c-d9e345f201a3)

**Comment by weishengbin** [comment]
已经解决，PACKAGE_ID有更新，还使用旧的就报错！

**Comment by pause125** [comment]
合约升级了。需要更新 package id。已更新。
